# Generated by Django 4.2 on 2023-04-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('date_start_registration', models.DateField(verbose_name='Дата начала регистрации')),
                ('date_end_registration', models.DateField(verbose_name='Дата окончания регистрации')),
                ('date_start_tournament', models.DateTimeField(verbose_name='Дата начала турнира')),
                ('date_end_tournament', models.DateTimeField(verbose_name='Дата окончания турнира')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer', verbose_name='Организатор')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'db_table': 'tournaments',
            },
        ),
    ]
