# Generated by Django 4.2 on 2023-05-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('title', models.CharField(max_length=50, verbose_name='Наименование')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
                ('date_start_registration', models.DateField(verbose_name='Дата начала регистрации')),
                ('date_end_registration', models.DateField(verbose_name='Дата окончания регистрации')),
                ('date_start_tournament', models.DateTimeField(verbose_name='Дата начала турнира')),
                ('date_end_tournament', models.DateTimeField(verbose_name='Дата окончания турнира')),
                ('image', models.ImageField(upload_to='tournaments/images/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'db_table': 'tournaments',
            },
        ),
        migrations.CreateModel(
            name='TournamentPlayer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player', verbose_name='Игрок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Участник турнира',
                'verbose_name_plural': 'Участники турнира',
                'db_table': 'tournament_players',
            },
        ),
    ]
