# Generated by Django 4.2 on 2023-04-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date_start_registration', models.DateField()),
                ('date_end_registration', models.DateField()),
                ('date_start_tournament', models.DateTimeField()),
                ('date_end_tournament', models.DateTimeField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizers.organizer')),
            ],
        ),
    ]
