# Generated by Django 4.2 on 2023-04-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='organizer',
        ),
        migrations.AddField(
            model_name='tournament',
            name='image',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
