# Generated by Django 4.2 on 2023-05-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentreferee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
