# Generated by Django 4.2 on 2023-04-13 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referees', '0001_initial'),
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('tournament_referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referees.tournamentreferee', verbose_name='Судья партии')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Партия игроков',
                'verbose_name_plural': 'Партии игроков',
                'db_table': 'game_players',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='winner_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.player', verbose_name='Победитель партии'),
        ),
    ]
