# Generated by Django 4.2 on 2023-05-01 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        ('referees', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament', verbose_name='Турнир'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='tournament_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentplayer', verbose_name='Игрок'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament_referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referees.tournamentreferee', verbose_name='Судья партии'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentplayer', verbose_name='Победитель партии'),
        ),
    ]
