# Generated by Django 4.2 on 2023-04-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='game',
            table='games',
        ),
        migrations.AlterModelTable(
            name='gameplayer',
            table='game_players',
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
    ]
