# Generated by Django 4.2 on 2023-05-01 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournamentplayer'),
        ('games', '0002_alter_player_name_alter_player_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentplayer', verbose_name='Победитель партии'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game', verbose_name='Партия'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournamentplayer', verbose_name='Игрок'),
        ),
    ]
